name: On push to main

on:
  push:
    branches:
      - main

# See: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: read
  pull-requests: read

# Only allow one build per PR source branch to run at once, cancelling in-progress
# builds when new builds arrive
# See: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idconcurrency
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.13.2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          # Just perform install
          runTests: false

      # Run e2e
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Already installed dependencies above
          install: false
          start: node app.js
          config-file: cypress.config.js
          # wait for 2 minutes for the server to respond
          wait-on: 'http://localhost:1337'
          wait-on-timeout: 120
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.github-token }}